### ISSUE TITLE
Make Documentation Easier to Use

### ISSUE THREAD

**Issue by markwilkie** [dotnet/dnceng#1179]
## Motivation

While we have plenty of documentation available to make our jobs easier, the location of the documents and the organization of these documents does not conform to any pattern. The goal behind this epic is to make it easier for the team to find the documents they need and to know where to put newly created documents. 

## Business Impact
By establishing a common "organizational structure" around out documentation, we will reduce the amount of time the team spends trying to find the documentation they are looking for. We will also be able to point our customers to documentation for their most commonly asked questions to reduce the randomization that comes into SSA. Both of these will be measured by comparing the number of requests we get for work that has been documented before this epic is completed and after. 

## Business Objects
- [ ] The team has guidelines for where to place a specific type of document they create
- [ ] We have established a process of managing the lifecycle of our documentation (i.e. keeping it up to date)
- [ ] We have established guidelines for organizing our documents 
- [ ] Apply the guidelines established above to our existing documentation
- [ ] The documentation is organized in such a way that DNCEng and our customer are able to easily find the documents they are looking for. 

## Milestones 

TBD
