### ISSUE TITLE
Make issues easier to use / find

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#125]
# Goals and motivation

While we have numerous issues in many repositories to track our work and avoid losing sight of potential future work, it's frequently difficult to find an issue. Part of this is because we have so many open issues. In addition, many issues are not in obvious buckets (are labelled incorrectly or the labels are vague) and we have _loads_ of buckets (labels). The goal behind this issue is to make it easier for DNCEng and our partners (customers) to find issues and know where to create new issues.

# Business objectives

Organizing our issues to make them easier to find will increase partner satisfaction and decrease the time our team spends looking for existing issues.

At a high level, we are working on separating documentation for our customers from what we need internally. This epic is about doing something similar with our issues as well as cleaning up other "noise" in the GitHub issue tabs in our repositories.

## Non-goals

Who works on an issue is separate from who may be interested in finding or filing the issue. It is not a goal (here at least) to reduce the number of places SSA or a v-team search to find what to work on next. The question shouldn't be about who works on them but who needs to know.

## Details

- [ ] We have established and / or refined existing guidelines for where to place new issues and how to label them
  - a pre-condition for this may be agreeing on the important types of issues
  - must go beyond something like "is it specific to repository X or more general"
- [ ] We have established processes for closing old issues that are no longer relevant
  - e.g., I recently noticed a Jenkins-specific issue somewhere 😬
- [ ] DNCEng and our customers know where to find relevant issues
- [ ] DNCEng and our customers know where to create new issues
- [ ] We have applied the above to existing issues and labels
  - i.e., at some point in time near the end of this epic, irrelevant labels are deleted and irrelevant issues are closed
- [ ] Issues that should be in an epic are

## Telemetry

Possible sources of telemetry include
- surveys if we get back to sending them out and aren't asking our customers the same questions too frequently
- counting requests that come in for ideas that already have an issue before and after completing this work

# Potential patterns

Essentially, extend dotnet/dnceng#647 to bucketize issues even more clearly

- make customer-relevant issues _really_ easy for them to find &mdash; w/o digging through minutia specific to internal DNCEng processes
  - solutioning: we might be able to do this using labels, projects that collect only customer-relevant issues, a separate repository for those issues, &hellip;
- reduce the number of labels we have, especially the vague ones
- increase label consistency across DNCEng repositories
- review existing issues to validate their labels make sense
  - e.g., if we really are the main owners of [dotnet/versions](https://github.com/dotnet/versions), add labels to issues there
- once we've done the migrations for dotnet/dnceng#647, confirm all GitHub repositories except [dotnet/dnceng](https://github.com/dotnet/dnceng) contain only issues specific to that repo
  - i.e., any issue that spans repositories must be in [dotnet/dnceng](https://github.com/dotnet/dnceng) or some other central repo to be named later
- GitHub issues that track AzDO issues are not in a torn state
  - somewhere or other, @garath mentioned he was considering automation to avoid having connections between a closed and an open issue

(My high order bit is keeping internal and customer-important issues separate. Your opinions may vary.)

## Existing categories

At a high level, @ilyas1974 pointed out the following existing buckets

Item | Location
-- | --
github issues related to an epic | github - dotnet/dnceng
Issue related to an infrastructure problem (non security) | github - dotnet/dnceng
Issue related to an infrastructure problem (security related) | AzDo Work Item (dnceng/internal) with "pointer issue" in github - dotnet/dnceng
Issues created for corporate compliance (e.g. S360, CG, etc) | AzDo Work Item (dnceng/internal) with "pointer issue" in github - dotnet/dnceng
Grafana alert (all) | github - dotnet/dnceng
Known Issue (using template to gather telemetry) for infrastructure problem | github - dotnet/dnceng
Critical Infrastructure Issue (tagged to display in Build Analysis) | github - dotnet/dnceng
Feature Request/bug fix for a service/tool in Arcade | github - dotnet/arcade

Known Issues and Critical Infrastructure Issues are of particular interest to customers. We will likely find we have other issues in [dotnet/dnceng](https://github.com/dotnet/dnceng) that are customer-relevant.

# Additional information

- this issue overlaps dotnet/dnceng#647 and is hopefully aligned with dotnet/dnceng#1179
- building here on a conversation started in [PR 132397, one pager for issue management and epic tracking for dnceng](https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/31160?_a=files&path=%2FDocumentation%2FOne-Pagers%2Fissue-management-and-epic-tracking-for-dnceng-arcade13131.md&discussionId=132397) and continued in [.NET Eng Services / General / I got issues... but you got them too](https://teams.microsoft.com/l/message/19:83953de1ddd34bcaa9ebaba54cb8eba4@thread.skype/1684341210737?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1684341210737&teamName=.NET%20Eng%20Services&channelName=General&createdTime=1684341210737)

**Comment by missymessa** [comment]
Issue management in dnceng is moving to AzDO. Closing this epic.
