### ISSUE TITLE
AzDO Issue #3521

### ISSUE THREAD

**Issue by mmitche** [dotnet/dnceng#1253]
[Azure Boards WorkItem](https://dev.azure.com/dnceng/internal/_workitems/edit/3521)

- [x] https://github.com/dotnet/dnceng/issues/1250
- [x] https://github.com/dotnet/dnceng/issues/1251
- [x] https://github.com/dotnet/dnceng/issues/1252
- [x] https://github.com/dotnet/arcade/issues/8172

**Comment by missymessa** [comment]
@mmitche the AzDO issue for this epic is closed. Should we close this epic?
