### ISSUE TITLE
Autoscaler vNext

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/dnceng#1267]
Migrated from https://github.com/dotnet/core-eng/issues/14851

@adiaaida wrote:

Bucket of issues for Autoscaler improvements

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [x] https://github.com/dotnet/core-eng/issues/11343
- [x] https://github.com/dotnet/core-eng/issues/11573
- [x] https://github.com/dotnet/core-eng/issues/11660
- [x] https://github.com/dotnet/core-eng/issues/13074
- [x] https://github.com/dotnet/core-eng/issues/13902
- [x] https://github.com/dotnet/core-eng/issues/14837
