### ISSUE TITLE
Improvements to the SSA and Ops Process

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#1289]
Get ops into a sustainable place, part 2. The goal of this Epic is to build upon the Ops and SSA processes created after the Snap by paving holes, smoothing rough edges, and fixing overlooked corners. This effort is specifically to support DNCEng, but should be easily adoptable by Product Construction as well.

Strategic goals:

- All members of the team feel comfortable triaging Ops issues
- Ops issues are being resolved at a rate sufficient to resolve critical issues in a timely manner
- Magnitude of and risk in Ops backlog can be easily understood by LT

Tactical goals:

**All members of the team feel comfortable triaging Ops issues**

- [ ] There is a Team Policy on triaging Ops issues
  - Includes guidance on identifying Faciley Ops, Regular Ops, and Epic Ops issues
  - Includes guidance on flagging impact / risk to service
  - Includes guidance on routine, expected issues (e.g. Component Governance)
  - Includes guidance on what actions may be considered for an Ops issue and how to select one - dnceng is no stranger to "not fitting the mold" (e.g., engaging with the assigning team to understand purpose and consider exception, requesting support from partner teams like DDFUN)
  - Includes process for updates or modifications to policy
  - The policy is understood and agreed to be sufficient by the team.

- [ ] There is Policy guiding Vendor involvement
  - Ensure close communication
    - Establish regular sync meetings between Vendor team and Ops Team
    - Establish dedicated Teams channel for Ops operations that includes Vendor team and dnceng team
  - Ensure clear expectations: Vendor-driven processes are documented in a single location
  - Ensure regular review of policy: There is a documented process for DNCEng team, Ops team or Vendor team to propose changes to policy.
  - The policy is understood and agreed to be sufficient by the team (including the Vendor members).

**Ops issues are being resolved at a rate sufficient to resolve critical issues in a timely manner**

- [ ] There is Policy guiding issue prioritization
  - Includes guidance on how any member may bring attention to an issue (e.g., re-triage to reevaluate the priority)
  - Includes guidance on additional processes that can be used to handle high issue counts (e.g., additional Ops persons on rotation, group related issues and create an epic)

**Magnitude of and risk in Ops backlog can be easily understood by LT**

- [ ] There are sufficient metrics at-hand for anyone to understand the state of the Ops backlog
  - Issue labels are sufficient for any metric pivot of interest (e.g., Compliance, S360, Component Governance, Helix Machines) and their use is clearly documented.
  - Metrics are automatically updated or generated

Non-goals:

- Rollouts are not under the Ops umbrella. It will continue to be managed by the Rollout V-Team.

**Comment by garath** [comment]
Epic writeup has been accepted by Mark and Ilya.
