### ISSUE TITLE
Secure supply chain for Docker images

### ISSUE THREAD

**Issue by epananth** [dotnet/dnceng#1845]
### Business Goal 

- [ ] Reasonably identify dockerfile that reference a managed dependency
- [ ] Ability to identify docker images generated by managed dockerfile 
- [ ] List all the managed dependencies 
- [ ] Reasonably identify docker images that reference a specific managed dependency

### Non Business Goal 
- [ ] Compliance / S360 
- [ ] Generated Dockerfile enforcement

### Implementation/Design Notes
- [ ] The tool updates existing dockerfile (as apposed to generating them)
- [ ] Comment tokens in dockerfile will be exploded with the actual managed docker command (e.g. RUN pypy)
- [ ] Tool will parse Docker FROM commands to determine build stages
- [ ] Managed dependencies and image layers available via web api
- [ ] Tool must be Integrated with existing Docker build process

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by MichaelSimons** [comment]
I have some questions/feedback on this.

1. I think it would be good to spell out what a managed dependency is in this context.
1. What is a managed docker file in this context?
1. "The tool updates existing docker files (as apposed to generating them)"  How does this relate to the business goals?  There is a disconnect for me in that this seems to imply being able to update the dependencies of our Dockerfiles.  Perhaps that is what is meant by "Managed" dependencies.
1. In the context of docker, dockerfile is one word. It is an industry standard/known convention.

**Comment by mthalman** [comment]
How does this plan relate to https://github.com/dotnet/dnceng/milestone/37?

> Tool will parse Docker FROM commands to determine build stages

For what purpose? Is this specifically referring to Dockerfile stages? Or is it about dependencies between Dockerfiles? Because that's a thing too. Each Dockerfile is used to produce an image, but some images are based on other images built from other Dockerfiles in the repo.

**Comment by epananth** [comment]
1. Managed Dependency : All the artifacts and the source of the docker image, that will be tracked in the tool will be considered as managed dependency.
Eg: Everything under FROM and RUN commands 
<img width="368" alt="image" src="https://github.com/dotnet/dnceng/assets/47157394/381c75e1-8d4d-4e89-957a-0796a140e4db">

2. The tool which we are planning to create will create docker snippets, we are referring to that as managed dockerfile ( more on this is coming in the one pager )
3. I think the one pager will bring more clarity to this question 
4. Noted, thanks for correcting

cc: @markwilkie

**Comment by epananth** [comment]
> How does this plan relate to https://github.com/dotnet/dnceng/milestone/37?
> 
> > Tool will parse Docker FROM commands to determine build stages
> 
> For what purpose? Is this specifically referring to Dockerfile stages? Or is it about dependencies between Dockerfiles? Because that's a thing too. Each Dockerfile is used to produce an image, but some images are based on other images built from other Dockerfiles in the repo.

We want to capture all the dependencies that the images based on other images are bringing in, so that we don't add the same dependencies over and over again. 

Like for eg: If Python is already installed in one of the images that is referenced in the main image, then we don't want to add the same thing again. We want to capture not only the image dependencies but also the images that are based on, those dependencies too. 

I think the one pager will bring clarity on the implementation plans, sorry about the confusion this has caused.

**Comment by MichaelSimons** [comment]
Thanks for the response @epananth, I look forward to reviewing the one pager.

**Comment by epananth** [comment]
> I'm still interested to understand how this relates to https://github.com/dotnet/dnceng/milestone/37? There was a lot of planning done there. Is this incorporating that plan or starting from scratch?

Sorry I missed this question. https://github.com/dotnet/dnceng/milestone/37 is the main epic/ milestone, this (meaning https://github.com/dotnet/dnceng/issues/1845) effort is a part of that epic, it has only few things in this epic (starting small here). 

I will try to connect both of them, to avoid any confusion. Thanks for pointing this out!

**Comment by epananth** [comment]
This epic shifted its focus. Ultimately, we developed a Power BI report on Docker end-of-life rather than dependency management.

Link to the report -> https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/98fbbdff-fe2c-4acd-b574-223be8b5b520/ReportSection0bbbaa94c27fd906b817?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47&experience=power-bi

Closing this epic.
