### ISSUE TITLE
Infrastructure to support .NET's adoption of the 1ES pipeline templates

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#2148]
Business objectives:

* [x] We have images that can run all our workloads with the 1ES templates in the existing 1ES hosted pools managed by engineering services.
* [ ] There are working copies of the official arcade templates in every supported branch of Arcade and product repos can use those templates to onboard to the 1ES pipeline templates
* [ ] There is guidance, a pattern and samples for authoring templates that can be shared between official and unofficial, and don't run excessive SDL scans.
* [x] A plan is in place for what functionality we want to keep in each set of templates.
