### ISSUE TITLE
Remove use of the `PublishCodeCoverageResults@v1` task

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#2307]
Azure DevOps has [blogged](https://devblogs.microsoft.com/devops/new-pccr-task/) about leaving [`PublishCodeCoverageResults@v1`](https://learn.microsoft.com/en-ca/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines) behind and moving to [`PublishCodeCoverageResults@v2`](https://learn.microsoft.com/en-ca/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines). Warnings about this deprecation have begun showing up in our builds.

An example warning from a recent [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596) build:
``` text
##[warning]New V2 version of task publishing code coverage results is available to all our customers now. We highly recommend to stop using the V1 version and migrate to V2 version (https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2). For more details, see - https://devblogs.microsoft.com/devops/new-pccr-task.
```

A fix here should cover at least the following repos and any servicing branches they may hold:
- [x] [dotnet/arcade-services](https://github.com/dotnet/arcade-services) &mdash; dotnet/arcade-services#3458
- [x] [dotnet/dnceng](https://github.com/dotnet/dnceng) &mdash; dotnet/dnceng#2420
- [x] [dotnet/dnceng-shared](https://github.com/dotnet/dnceng-shared) &mdash; dotnet/dnceng-shared#62
- [x] [dotnet-helix-machines](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines) &mdash; [!38625](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38625)
- [x] [dotnet-helix-service](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service) &mdash; [!38673](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/38673)

### Notes

1. the list above may not be comprehensive. I did not check every repository we own for use of the `PublishCodeCoverageResults@v1` task
2. task parameters for `PublishCodeCoverageResults@v2` no longer include `codeCoverageTool`. we should remove this parameter as part of the migration.
3. the `additionalCodeCoverageFiles` parameter passed to `PublishCodeCoverageResults@v1` in a few of our pipelines does not actually exist. should remove this parameter as well to avoid confusion going forward.

### Discussion

We talked about this internally and in [!38625](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38625). The upshot was nobody had looked at the coverage reports in years and everyone was fine removing the code coverage infrastructure we have in place. We are going to remove the tasks and related bits.

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Removed unnecessary and unused code coverage infrastructure from a few DNCEng repositories.

**Comment by dougbu** [comment]
In addition `publishRunAttachments` is a parameter of `PublishTestResults@2` and `VSTest@3` but neither [`PublishCodeCoverageResults@v1`](https://learn.microsoft.com/en-ca/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines) nor [`PublishCodeCoverageResults@v2`](https://learn.microsoft.com/en-ca/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v2?view=azure-pipelines). Should remove that parameter here too.

**Comment by dougbu** [comment]
@tkapin, @premun, @dkurepa, @andriipatsula, @oleksandr-didyk, @MilenaHristova this issue and our removal choice is of course not binding on your team. Would you appreciate a PR for [dotnet/arcade-services](https://github.com/dotnet/arcade-services)❔ If not, I'll remove it from my checklist.

**Comment by dougbu** [comment]
PRs are all in. Just waiting for merges into 'production' branches, at which point all in-use branches will no longer have code coverage infrastructure.

**Comment by dougbu** [comment]
done
