### ISSUE TITLE
Migrate Services To Use Entra Managed Identities And Permissions Instead Of Secret Values To Improve Security And Reduce Maintenance Costs And Down Time

### ISSUE THREAD

**Issue by davfost** [dotnet/dnceng#2384]
Migrate Services To Use Entra Managed Identities And Permissions Instead Of Secret Values Such As Connection Strings And PAT Tokens To Improve Security And Reduce Maintenance Costs And Down Time For Secret Rotations.

# Business Impact:

- Reduce the attack surface of services by eliminating secrets that can be exposed though out process workflows.
- Reduce the maintenance costs for service by eliminating reoccurring secret rotation activates.
- Reduce service down times by eliminating the connectivity disruptions caused when secrets are rotated.

# Business Objectives:

**For All Targeted Services:**

- Eliminate all secret values that can be replaced with managed identities and resource permissions configuration
- Eliminate all key vault resources that are no longer needed
- Correct permissions are assigned for all managed identities so existing service workflows continue to function without secrets

**Out Of Scope:**

- Secret changes for how clients access to services.
    - Service should not know or be responsible for client secrets.
    - Depending on how a service is interacted with it may require new protocols that have to be updated on both ends of communications to handle changes in how clients interact with services.

# Milestones

- [ ] Identify all service we want to migrate

**For Each Targeted Service:**
- [ ] Identify all secrets that **can** be migrated and categorize them
    - Service Resource (Secrets used to access resources that are clearly owned by the service itself)
    - Service Dependency (Secrets used to access other services or resources that are not clearly owned by the service itself)
    - Other (Secrets that are not clearly used by the service in order for it to function)
- [ ] For each secret that can be migrated make code updates and permission modification to replace the secret values with managed identify access and disable the existing secret (don't delete it)
- [ ] After all secrets have been migrated to managed identities and all secretes are verified as 'disabled' put the Key Vault on life support for N months.

**After All Services Are Updated:**

- [ ] Once the service has been confirmed as running and stable using only managed identities delete key vaults that are no longer needed.

**_Should we proactively archive secret rotation instruction for service or just let them stagnate?_**

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Updating services to use managed identities instead of secretes for resource access.
