### ISSUE TITLE
CloudTest Exploration

### ISSUE THREAD

**Issue by chcosta** [dotnet/dnceng#427]
## Context

We currently have a competing offering for CloudTest called Helix.  There are a number of motivations for exploring a move to CloudTest.

- Helix is a large ongoing cost for our team.  The "cost" is spread across supporting the Helix service, Helix Sdk, Helix Api, and Helix machines.  We are constantly investing in either ensuring sufficient system uptime or in meeting the evolving Microsoft security requirements; leaving us little time to invest in features our customers are asking for.
- CloudTest provides either parity or an improved feature set for *most* of the scenarios that Helix targets.
- The 1ES team (not us) is tasked with ensuring CloudTest meets all Microsoft security requirements
- CloudTest is the well-known, widely accepted large-scale testing solution within Microsoft

The primary goal of this effort is to validate CloudTest is a viable solution for the .NET product.

## Business Objectives

- [x] Criteria for making a decision on whether to move to CloudTest is defined
- [ ] .NET Engineering has enough context / info to make a decision on whether to pursue adoption of CloudTest
- [ ] 1ES is in alignment with our CloudTest investment decisions

## Meeting Recordings

- May 4, 2023 - CloudTest overview for .NET Engineering team - [Meeting link](https://microsoft-my.sharepoint.com/:v:/p/chcosta/EYlpO9Iar-NFqsN6qgemu1kBcztQdFPs039rsjxiwbgnxw?e=Ii59Hq)
- May 15, 2023 - Discuss unauthenticated CloudTest prototype with CloudTest team - [Meeting link](https://microsoft-my.sharepoint.com/:v:/p/chcosta/EW6zMon_b_xKtvQgybn56eUBcjftSfrsdb1m5bG9OF52UA?e=FOrKZ0)
- June 19, 2023 - Walk-through .NET CloudTest user scenarios - [Meeting link](https://microsoft-my.sharepoint.com/:v:/p/chcosta/ESGmvitDUABAk-MFUJT1mmMBz8iCAbVrOy8Yr_vHHloQ7w?e=diTW79)
