### ISSUE TITLE
DevWF: Filter Build Analysis By Pipeline

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#556]
## Motivation and Business Impact

In an effort to improve the developer workflow experience, particularly for the dotnet/runtime team and contributors, the following functionality should be added to Build Analysis so the Runtime team can make "build analysis green" a requisite for merging a pull request. To achieve this, the following features has been requested:

## Business Objectives

- [ ] Product repos have a way to omit the results from specific Azure DevOps pipelines from Build Analysis
- [ ] Pull Requests have the ability to include a justification for merging-on-red
- [ ] Users have a way to validate the regex used for a Known Issue

## Functional Deliverables

- [x] **Pipeline filtering**: Allow repositories to define which pipelines are going to be analyzed by build analysis, for example, the runtime team only needs the runtime pipeline to determine if a pull request is successful, and they can ignore the results of other pipelines such as runtime-extra-platforms, which is unstable and optional. The runtime pipeline is the only one that is automatically triggered when a pull request is created, and it is the main criterion for merging.
- [x] **Escape mechanism**: Allow users to override the build analysis status by adding a comment to the pull request that explains why they want to merge on red. 
- [x] **Validation improvement**: Provide a more robust and faster way to validate regex messages. We are still in discussion with the runtime team about our role in this feature.

**Comment by AlitzelMendez** [comment]
> [!IMPORTANT]
> This epic is now finished 😄  All the functional deliverables have been delivered. 🥳 🎈 
 > Thank you, everyone!! Especially @missymessa and @riarenas, it has been a pleasure to work with both of you!!!
