### ISSUE TITLE
Milestone Management in dotnet/dnceng

### ISSUE THREAD

**Issue by missymessa** [dotnet/dnceng#646]
- [x] When an epic issue is closed, the associated milestone is also closed. Do not allow an epic to be closed if there are still open issues associated with that epic's milestone. 
- [x] When an epic label is added to an issue, include the title of that issue in the list of milestones
- [x] When an epic issue's title is updated, update the name in the milestones
- [x] Do not allow an epic label to be removed from an epic if any open issues are still associated with it
- [x] Make this webhook usage opt-in (config file) per repo
- [x] Document how this webhook works

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release notes required

**Comment by missymessa** [comment]
This was rolled out and verified that it's working.
